# Statistical Analytic Methods
#### Prof. KKIM, Yonsei University
### LEC07. EDA

In [1]:
import pandas as pd
import numpy as np
sample_1 = pd.read_csv('/content/drive/MyDrive/[YU]/[Lecture]/[SAM]/01_SAM_Practice/SAM_LEC07/sample_1_new.csv')
sample_1.head()

   Name  age        major  score grade
0   Kim   23   management   95.0     A
1  Park   22    economics    NaN     A
2   Ban   23   management   82.0     B
3  Choi   21       design   87.0     B
4   Han   21  engineering   86.0     B

## Checking Missing Values

In [2]:
sample_1.isnull()

    Name    age  major  score  grade
0  False  False  False  False  False
1  False  False  False   True  False
2  False  False  False  False  False
3  False  False  False  False  False
4  False  False  False  False  False
5  False  False  False  False  False
6  False  False  False   True  False
7  False  False  False  False  False
8  False  False  False  False  False
9  False  False  False  False  False

In [3]:
sample_1.notnull()

   Name   age  major  score  grade
0  True  True   True   True   True
1  True  True   True  False   True
2  True  True   True   True   True
3  True  True   True   True   True
4  True  True   True   True   True
5  True  True   True   True   True
6  True  True   True  False   True
7  True  True   True   True   True
8  True  True   True   True   True
9  True  True   True   True   True

In [4]:
sample_1.isnull().any()

Name     False
age      False
major    False
score     True
grade    False
dtype: bool

In [5]:
sample_1.isnull().any().any()

np.True_

## Checking Frequency of Missing Values

In [6]:
1 == True

True

In [7]:
0 == False

True

In [8]:
sample_1.isnull().sum()

Name     0
age      0
major    0
score    2
grade    0
dtype: int64

In [9]:
type(sample_1.isnull())

pandas.core.frame.DataFrame

In [10]:
type(sample_1.isnull().sum())

pandas.core.series.Series

In [11]:
sample_1.notnull().sum()

Name     10
age      10
major    10
score     8
grade    10
dtype: int64

In [12]:
sample_1.notnull().sum().sort_values(ascending=True)

score     8
Name     10
age      10
major    10
grade    10
dtype: int64

In [13]:
sample_1.notnull().sum().sort_values(ascending=False)

Name     10
age      10
major    10
grade    10
score     8
dtype: int64

## Finding Missing Values

In [14]:
pd.Series([True,False]*5)

0     True
1    False
2     True
3    False
4     True
5    False
6     True
7    False
8     True
9    False
dtype: bool

In [15]:
sample_1[pd.Series([True,False]*5)]

  Name  age        major  score grade
0  Kim   23   management   95.0     A
2  Ban   23   management   82.0     B
4  Han   21  engineering   86.0     B
6  Lee   22  engineering    NaN     B
8   Ki   20          law   78.0     C

In [16]:
sample_1['score'].isnull()

0    False
1     True
2    False
3    False
4    False
5    False
6     True
7    False
8    False
9    False
Name: score, dtype: bool

In [17]:
sample_1[sample_1['score'].isnull()]

   Name  age        major  score grade
1  Park   22    economics    NaN     A
6   Lee   22  engineering    NaN     B

In [18]:
sample_1[sample_1['score'].notnull()]

    Name  age        major  score grade
0    Kim   23   management   95.0     A
2    Ban   23   management   82.0     B
3   Choi   21       design   87.0     B
4    Han   21  engineering   86.0     B
5  Hwang   24    economics   85.0     B
7   Jang   24         math   75.0     C
8     Ki   20          law   78.0     C
9   Yang   23   statistics   68.0     D

## Handling Missing Values

### Remove

In [20]:
sample_1.dropna()

    Name  age        major  score grade
0    Kim   23   management   95.0     A
2    Ban   23   management   82.0     B
3   Choi   21       design   87.0     B
4    Han   21  engineering   86.0     B
5  Hwang   24    economics   85.0     B
7   Jang   24         math   75.0     C
8     Ki   20          law   78.0     C
9   Yang   23   statistics   68.0     D

In [21]:
sample_1.dropna(axis=0)

    Name  age        major  score grade
0    Kim   23   management   95.0     A
2    Ban   23   management   82.0     B
3   Choi   21       design   87.0     B
4    Han   21  engineering   86.0     B
5  Hwang   24    economics   85.0     B
7   Jang   24         math   75.0     C
8     Ki   20          law   78.0     C
9   Yang   23   statistics   68.0     D

In [22]:
sample_1.dropna(axis=1)

    Name  age        major grade
0    Kim   23   management     A
1   Park   22    economics     A
2    Ban   23   management     B
3   Choi   21       design     B
4    Han   21  engineering     B
5  Hwang   24    economics     B
6    Lee   22  engineering     B
7   Jang   24         math     C
8     Ki   20          law     C
9   Yang   23   statistics     D

In [23]:
sample_1.dropna(how='any')

    Name  age        major  score grade
0    Kim   23   management   95.0     A
2    Ban   23   management   82.0     B
3   Choi   21       design   87.0     B
4    Han   21  engineering   86.0     B
5  Hwang   24    economics   85.0     B
7   Jang   24         math   75.0     C
8     Ki   20          law   78.0     C
9   Yang   23   statistics   68.0     D

In [24]:
sample_1.dropna(how='all')

    Name  age        major  score grade
0    Kim   23   management   95.0     A
1   Park   22    economics    NaN     A
2    Ban   23   management   82.0     B
3   Choi   21       design   87.0     B
4    Han   21  engineering   86.0     B
5  Hwang   24    economics   85.0     B
6    Lee   22  engineering    NaN     B
7   Jang   24         math   75.0     C
8     Ki   20          law   78.0     C
9   Yang   23   statistics   68.0     D

In [25]:
sample_1.dropna(inplace=False)
sample_1

    Name  age        major  score grade
0    Kim   23   management   95.0     A
1   Park   22    economics    NaN     A
2    Ban   23   management   82.0     B
3   Choi   21       design   87.0     B
4    Han   21  engineering   86.0     B
5  Hwang   24    economics   85.0     B
6    Lee   22  engineering    NaN     B
7   Jang   24         math   75.0     C
8     Ki   20          law   78.0     C
9   Yang   23   statistics   68.0     D

### Fill

In [26]:
sample_1.fillna(0)

    Name  age        major  score grade
0    Kim   23   management   95.0     A
1   Park   22    economics    0.0     A
2    Ban   23   management   82.0     B
3   Choi   21       design   87.0     B
4    Han   21  engineering   86.0     B
5  Hwang   24    economics   85.0     B
6    Lee   22  engineering    0.0     B
7   Jang   24         math   75.0     C
8     Ki   20          law   78.0     C
9   Yang   23   statistics   68.0     D

In [27]:
sample_1.fillna(method='backfill')

/tmp/ipykernel_7547/2640733520.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  sample_1.fillna(method='backfill')

    Name  age        major  score grade
0    Kim   23   management   95.0     A
1   Park   22    economics   82.0     A
2    Ban   23   management   82.0     B
3   Choi   21       design   87.0     B
4    Han   21  engineering   86.0     B
5  Hwang   24    economics   85.0     B
6    Lee   22  engineering   75.0     B
7   Jang   24         math   75.0     C
8     Ki   20          law   78.0     C
9   Yang   23   statistics   68.0     D

In [28]:
sample_1.fillna(method='pad')

/tmp/ipykernel_7547/2064237017.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  sample_1.fillna(method='pad')

    Name  age        major  score grade
0    Kim   23   management   95.0     A
1   Park   22    economics   95.0     A
2    Ban   23   management   82.0     B
3   Choi   21       design   87.0     B
4    Han   21  engineering   86.0     B
5  Hwang   24    economics   85.0     B
6    Lee   22  engineering   85.0     B
7   Jang   24         math   75.0     C
8     Ki   20          law   78.0     C
9   Yang   23   statistics   68.0     D

In [29]:
sample_1.fillna(method='ffill')

/tmp/ipykernel_7547/2779197019.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  sample_1.fillna(method='ffill')

    Name  age        major  score grade
0    Kim   23   management   95.0     A
1   Park   22    economics   95.0     A
2    Ban   23   management   82.0     B
3   Choi   21       design   87.0     B
4    Han   21  engineering   86.0     B
5  Hwang   24    economics   85.0     B
6    Lee   22  engineering   85.0     B
7   Jang   24         math   75.0     C
8     Ki   20          law   78.0     C
9   Yang   23   statistics   68.0     D

### Replace

In [30]:
sample_1.replace(to_replace =np.nan,
                 value = 0)

    Name  age        major  score grade
0    Kim   23   management   95.0     A
1   Park   22    economics    0.0     A
2    Ban   23   management   82.0     B
3   Choi   21       design   87.0     B
4    Han   21  engineering   86.0     B
5  Hwang   24    economics   85.0     B
6    Lee   22  engineering    0.0     B
7   Jang   24         math   75.0     C
8     Ki   20          law   78.0     C
9   Yang   23   statistics   68.0     D

### Interpolation

In [31]:
sample_1.interpolate(method ='linear')

/tmp/ipykernel_7547/2195883872.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  sample_1.interpolate(method ='linear')

    Name  age        major  score grade
0    Kim   23   management   95.0     A
1   Park   22    economics   88.5     A
2    Ban   23   management   82.0     B
3   Choi   21       design   87.0     B
4    Han   21  engineering   86.0     B
5  Hwang   24    economics   85.0     B
6    Lee   22  engineering   80.0     B
7   Jang   24         math   75.0     C
8     Ki   20          law   78.0     C
9   Yang   23   statistics   68.0     D

### Practice

In [ ]:
import pandas as pd
employee = pd.read_csv('/content/drive/MyDrive/[YU]/[Lecture]/[SAM]/01_SAM_Practice/SAM_LEC06/employee.csv')
employee.head()

,UNIQUE_ID,POSITION_TITLE,DEPARTMENT,BASE_SALARY,RACE,EMPLOYMENT_TYPE,GENDER,EMPLOYMENT_STATUS,HIRE_DATE,JOB_DATE
0,0,ASSISTANT DIRECTOR (EX LVL),Municipal Courts Department,121862.0,Hispanic/Latino,Full Time,Female,Active,2006-06-12,2012-10-13
1,1,LIBRARY ASSISTANT,Library,26125.0,Hispanic/Latino,Full Time,Female,Active,2000-07-19,2010-09-18
2,2,POLICE OFFICER,Houston Police Department-HPD,45279.0,White,Full Time,Male,Active,2015-02-03,2015-02-03
3,3,ENGINEER/OPERATOR,Houston Fire Department (HFD),63166.0,White,Full Time,Male,Active,1982-02-08,1991-05-25
4,4,ELECTRICIAN,General Services Department,56347.0,White,Full Time,Male,Active,1989-06-19,1994-10-22

In [ ]:
# What are the names of columns?
employee.columns

Index(['UNIQUE_ID', 'POSITION_TITLE', 'DEPARTMENT', 'BASE_SALARY', 'RACE',
       'EMPLOYMENT_TYPE', 'GENDER', 'EMPLOYMENT_STATUS', 'HIRE_DATE',
       'JOB_DATE'],
      dtype='object')

In [ ]:
# How many number of rows and columns are there?
employee.shape

(2000, 10)

In [ ]:
# Is there any missing value?
employee.isnull().any().any()

np.True_

In [ ]:
# Find the rows where the value of RACE is missing.
employee[employee.RACE.isnull()]

,UNIQUE_ID,POSITION_TITLE,DEPARTMENT,BASE_SALARY,RACE,EMPLOYMENT_TYPE,GENDER,EMPLOYMENT_STATUS,HIRE_DATE,JOB_DATE
9,9,AIRPORT OPERATIONS COORDINATOR,Houston Airport System (HAS),44616.0,NaN,Full Time,Male,Active,2016-03-14,2016-03-14
31,31,FIRE FIGHTER TRAINEE,Houston Fire Department (HFD),28024.0,NaN,Full Time,Male,Active,2016-03-14,2016-03-14
101,101,CUSTOMER SERVICE CLERK,Library,NaN,NaN,Part Time,Female,Active,2016-02-29,2016-02-29
201,201,SENIOR REFUSE TRUCK DRIVER,Solid Waste Management,33675.0,NaN,Full Time,Male,Active,2014-03-03,2014-03-03
334,334,COMMUNITY RELATIONS SPECIALIST,Health & Human Services,NaN,NaN,Part Time,Female,Active,2016-05-23,2016-05-23
350,350,CUSTOMER SERVICE REPRESENTATIVE II,Fleet Management Department,33363.0,NaN,Full Time,Male,Active,2016-05-31,2016-05-31
471,471,FIRE FIGHTER TRAINEE,Houston Fire Department (HFD),28024.0,NaN,Full Time,Male,Active,2016-03-28,2016-03-28
494,494,IT LEAD - CLIENT SUPPORT,Houston Airport System (HAS),80002.0,NaN,Full Time,Male,Active,2016-02-01,2016-02-01
500,500,LICENSED VOCATIONAL NURSE,Health & Human Services,49400.0,NaN,Full Time,Female,Active,2016-02-08,2016-02-08
519,519,9-1-1 TELECOMMUNICATOR,Houston Emergency Center (HEC),31200.0,NaN,Full Time,Female,Active,2016-04-25,2016-04-25
569,569,POLICE TRAINEE,Houston Police Department-HPD,42000.0,NaN,Full Time,Male,Active,2016-02-08,2016-02-08
639,639,RECREATION SPECIALIST,Parks & Recreation,28808.0,NaN,Full Time,Male,Active,2016-02-29,2016-02-29
652,652,CUSTOMER SERVICE REPRESENTATIVE II,Admn. & Regulatory Affairs,32448.0,NaN,Full Time,Female,Active,2016-05-03,2016-05-03
704,704,POLICE TRAINEE,Houston Police Department-HPD,42000.0,NaN,Full Time,Male,Active,2016-02-08,2016-02-08
774,774,PARK MAINTENANCE AIDE,Parks & Recreation,NaN,NaN,Part Time,Male,Active,2016-04-04,2016-04-04
819,819,COMMUNITY RELATIONS SPECIALIST,Parks & Recreation,NaN,NaN,Temporary,Female,Active,2016-05-31,2016-05-31
836,836,LIBRARY SERVICE SPECIALIST,Library,32157.0,NaN,Full Time,Female,Active,2014-05-27,2014-05-27
991,991,PARKING ENFORCEMENT OFFICER,Admn. & Regulatory Affairs,27581.0,NaN,Full Time,Male,Active,2016-02-11,2016-02-11
997,997,POLICE TRAINEE,Houston Police Department-HPD,42000.0,NaN,Full Time,Female,Active,2016-02-08,2016-02-08
1000,1000,MECHANIC HELPER,Fleet Management Department,27539.0,NaN,Full Time,Male,Active,2016-04-11,2016-04-11
1051,1051,SENIOR REFUSE TRUCK DRIVER,Solid Waste Management,31803.0,NaN,Full Time,Male,Active,2016-03-14,2016-03-14
1068,1068,POLICE TRAINEE,Houston Police Department-HPD,42000.0,NaN,Full Time,Female,Active,2016-02-08,2016-02-08
1109,1109,POLICE TRAINEE,Houston Police Department-HPD,42000.0,NaN,Full Time,Female,Active,2016-02-08,2016-02-08
1140,1140,SIDELOADER OPERATOR,Solid Waste Management,30410.0,NaN,Full Time,Male,Active,2016-03-28,2016-03-28
1179,1179,SENIOR PROCUREMENT SPECIALIST,Finance,72500.0,NaN,Full Time,Male,Active,2016-03-28,2016-03-28
1189,1189,COUNCIL ADMINISTRATIVE ASSISTANT (EXECUT,City Council,45000.0,NaN,Full Time,Female,Active,2016-02-15,2016-02-15
1243,1243,SIDELOADER OPERATOR,Solid Waste Management,30410.0,NaN,Full Time,Male,Active,2016-02-01,2016-02-01
1258,1258,FIRE FIGHTER TRAINEE,Houston Fire Department (HFD),28024.0,NaN,Full Time,Male,Active,2016-03-14,2016-03-14
1363,1363,AIRPORT COMMUNICATIONS OPERATOR,Houston Airport System (HAS),33717.0,NaN,Full Time,Female,Active,2016-02-01,2016-02-01
1439,1439,ANIMAL ENFORCEMENT OFFICER TRAINEE,Admn. & Regulatory Affairs,36400.0,NaN,Full Time,Male,Active,2016-05-10,2016-05-10
1506,1506,COUNCIL SECRETARY (EXECUTIVE LEVEL),City Council,40000.0,NaN,Full Time,Female,Active,2016-04-11,2016-04-11
1731,1731,FIRE FIGHTER TRAINEE,Houston Fire Department (HFD),28024.0,NaN,Full Time,Male,Active,2016-03-28,2016-03-28
1753,1753,RECREATION SPECIALIST,Parks & Recreation,28766.0,NaN,Full Time,Female,Active,2016-03-14,2016-03-14
1792,1792,LIFEGUARD,Parks & Recreation,NaN,NaN,Temporary,Male,Active,2016-05-21,2016-05-21
1898,1898,FIRE FIGHTER TRAINEE,Houston Fire Department (HFD),28024.0,NaN,Full Time,Male,Active,2016-03-28,2016-03-28

In [ ]:
employee.melt(id_vars='UNIQUE_ID',
              value_vars=['POSITION_TITLE', 'DEPARTMENT', 'BASE_SALARY', 'RACE', 'EMPLOYMENT_TYPE',
                          'GENDER', 'EMPLOYMENT_STATUS', 'HIRE_DATE','JOB_DATE'],
#              value_vars=employee.columns.difference(['UNIQUE_ID']),
              var_name='VariableType',
              value_name='Value').head()

   UNIQUE_ID    VariableType                        Value
0          0  POSITION_TITLE  ASSISTANT DIRECTOR (EX LVL)
1          1  POSITION_TITLE            LIBRARY ASSISTANT
2          2  POSITION_TITLE               POLICE OFFICER
3          3  POSITION_TITLE            ENGINEER/OPERATOR
4          4  POSITION_TITLE                  ELECTRICIAN