# Statistical Analytic Methods
#### Prof. KKIM, Yonsei University
### LEC03. Data Manipulation

### List

In [ ]:
num_list = [1, 2, 3, 4]
num_list

[1, 2, 3, 4]

In [ ]:
aa, bb, cc, dd = num_list
print(aa, bb, cc, dd)

1 2 3 4

In [ ]:
midterm_score = [84, 23, 92, 17, 88]
assignment_score = [88, 87, 90, 88, 89]
final_score = [71, 99, 78, 89, 82]
total_score = [midterm_score, assignment_score, final_score]
total_score

[[84, 23, 92, 17, 88], [88, 87, 90, 88, 89], [71, 99, 78, 89, 82]]

In [ ]:
total_score[2][3]

89

#### Practice

In [ ]:
# What are the expected results?
fruits = ["apple", "banana", "cherry", "mango", "pear"]
print(len(fruits))

5

In [ ]:
numbers = [10, 20, 30, 40, 50]
numbers[2] = 100
print(numbers)

[10, 20, 100, 40, 50]

In [ ]:
colors = ["red", "blue", "green"]
colors.append("yellow")
print(colors)

['red', 'blue', 'green', 'yellow']

In [ ]:
list1 = [1, 2, 3]
list2 = [4, 5, 6]
combined = list2 + list1; print(combined)

[4, 5, 6, 1, 2, 3]

In [ ]:
my_list = ["Yes", "No", 1, 1, 4, 5, [2,4]]
my_list[0]

'Yes'

In [ ]:
my_list[1]

'No'

In [ ]:
my_list[0]+my_list[1]

'YesNo'

In [ ]:
my_list[2]+my_list[3]

2

In [ ]:
my_list[0:2]

['Yes', 'No']

In [ ]:
my_list[:2]

['Yes', 'No']

In [ ]:
my_list[2:]

[1, 1, 4, 5, [2, 4]]

In [ ]:
my_list[:]

['Yes', 'No', 1, 1, 4, 5, [2, 4]]

In [ ]:
my_list[-1]

[2, 4]

In [ ]:
my_list[-1][0]

2

#### Practice

In [ ]:
# What will be the expected result?
ChristmasGift = ['MacBook', 'iPhone', 'Bitcoin', 'Tesla', '1', 2, '3', 4]

In [ ]:
print(ChristmasGift[:2])

['MacBook', 'iPhone']

In [ ]:
print(ChristmasGift[4:6])

['1', 2]

In [ ]:
print(ChristmasGift[0:3])

['MacBook', 'iPhone', 'Bitcoin']

In [ ]:
print(ChristmasGift[:])

['MacBook', 'iPhone', 'Bitcoin', 'Tesla', '1', 2, '3', 4]

#### Practice

In [ ]:
# Store the five names in a list called students.
students = ["John", "James", "BoA", "Tanaka", "Kim"]

In [ ]:
# Store the scores in a nested list called scores, with one inner list for each exam.
scores = [
    [84, 23, 92, 17, 88],  # Midterm
    [88, 87, 90, 88, 89],  # Assignment
    [71, 99, 78, 89, 82]   # Final
]
scores

[[84, 23, 92, 17, 88], [88, 87, 90, 88, 89], [71, 99, 78, 89, 82]]

In [ ]:
# Using indexing, print Tanaka’s final exam score and BoA’s assignment score.
print(scores[2][3])  # 89
print(scores[1][2])  # 90

89
90

In [ ]:
# Tanaka’s midterm score was entered incorrectly. Change it from 17 to 77.
scores[0][3] = 77
scores

[[84, 23, 92, 77, 88], [88, 87, 90, 88, 89], [71, 99, 78, 89, 82]]

In [ ]:
# Calculate Tanaka’s total score using values from the nested list.
tanaka_total = scores[0][3] + scores[1][3] + scores[2][3]
print(tanaka_total)  # 254

254

In [ ]:
# Create a new list containing only John’s three scores. Do not type the scores again.
john_scores = [scores[0][0], scores[1][0], scores[2][0]]
print(john_scores)  # [84, 88, 71]

[84, 88, 71]

### Dictionary

In [ ]:
my_dict = {'Name':'Kim',
           'Nationality':'Korea',
           'Age':21,
           'IntSTP':'A+'}
my_dict

{'Name': 'Kim', 'Nationality': 'Korea', 'Age': 21, 'IntSTP': 'A+'}

In [ ]:
type(my_dict)

dict

In [ ]:
len(my_dict)

4

In [ ]:
my_dict.keys()

dict_keys(['Name', 'Nationality', 'Age', 'IntSTP'])

In [ ]:
my_dict.values()

dict_values(['Kim', 'Korea', 21, 'A+'])

In [ ]:
my_dict['gender']='M'
print(my_dict)

{'Name': 'Kim', 'Nationality': 'Korea', 'Age': 21, 'IntSTP': 'A+', 'gender': 'M'}

In [ ]:
my_dict['Gender']='F'
print(my_dict)

{'Name': 'Kim', 'Nationality': 'Korea', 'Age': 21, 'IntSTP': 'A+', 'gender': 'M', 'Gender': 'F'}

In [ ]:
my_dict['IntSTP']='B+'
print(my_dict)

{'Name': 'Kim', 'Nationality': 'Korea', 'Age': 21, 'IntSTP': 'B+', 'gender': 'M', 'Gender': 'F'}

In [ ]:
del my_dict['gender']
print(my_dict)

{'Name': 'Kim', 'Nationality': 'Korea', 'Age': 21, 'IntSTP': 'B+', 'Gender': 'F'}

#### Practice

In [ ]:
# Create a dictionary
# Stage Name: SAM
# Debut Year: 2026
# Agency: Yonsei Entertainment
# Positions: Main Vocal, Lead Dancer, Maknae
# Chart Records: 1st on Melon Chart, 15th on Billboard Chart

In [ ]:
idol_profile = {
    "Stage Name": "SAM",
    "Debut Year": 2026,
    "Agency": "Python Entertainment",

    "Positions": ["Main Vocal", "Lead Dancer", "Maknae"],

    "Chart Records": {
        "Melon Chart": 1,
        "Billboard Chart": 15
    }
}
idol_profile

{'Stage Name': 'SAM',
 'Debut Year': 2026,
 'Agency': 'Python Entertainment',
 'Positions': ['Main Vocal', 'Lead Dancer', 'Maknae'],
 'Chart Records': {'Melon Chart': 1, 'Billboard Chart': 15}}

#### Practice

In [ ]:
student_scores = {
    "John":   {"midterm": 84, "assignment": 88, "final": 71},
    "James":  {"midterm": 23, "assignment": 87, "final": 99},
    "BoA":    {"midterm": 92, "assignment": 90, "final": 78},
    "Tanaka": {"midterm": 77, "assignment": 88, "final": 89},
    "Kim":    {"midterm": 88, "assignment": 89, "final": 82}
}
student_scores

{'John': {'midterm': 84, 'assignment': 88, 'final': 71},
 'James': {'midterm': 23, 'assignment': 87, 'final': 99},
 'BoA': {'midterm': 92, 'assignment': 90, 'final': 78},
 'Tanaka': {'midterm': 77, 'assignment': 88, 'final': 89},
 'Kim': {'midterm': 88, 'assignment': 89, 'final': 82}}

In [ ]:
# Retrieve Tanaka’s final exam score without using a numerical index.
print(student_scores["Tanaka"]["final"])  # 89

89

In [ ]:
# James completed an additional assignment and his assignment score changed to 92. Update the dictionary.
student_scores["James"]["assignment"] = 92
student_scores

{'John': {'midterm': 84, 'assignment': 88, 'final': 71},
 'James': {'midterm': 23, 'assignment': 92, 'final': 99},
 'BoA': {'midterm': 92, 'assignment': 90, 'final': 78},
 'Tanaka': {'midterm': 77, 'assignment': 88, 'final': 89},
 'Kim': {'midterm': 88, 'assignment': 89, 'final': 82}}

In [ ]:
# Add "participation": 95 to BoA’s record. Calculate BoA’s weighted course score
# using 30% midterm, 20% assignment, 40% final, and 10% participation.
student_scores["BoA"]["participation"] = 95
student_scores["BoA"]["course_score"] = (
    student_scores["BoA"]["midterm"] * 0.30
    + student_scores["BoA"]["assignment"] * 0.20
    + student_scores["BoA"]["final"] * 0.40
    + student_scores["BoA"]["participation"] * 0.10
)
student_scores

{'John': {'midterm': 84, 'assignment': 88, 'final': 71},
 'James': {'midterm': 23, 'assignment': 92, 'final': 99},
 'BoA': {'midterm': 92,
  'assignment': 90,
  'final': 78,
  'participation': 95,
  'course_score': 86.3},
 'Tanaka': {'midterm': 77, 'assignment': 88, 'final': 89},
 'Kim': {'midterm': 88, 'assignment': 89, 'final': 82}}

### DataFrame

In [ ]:
myClass={'city': ['Dublin','Dublin','Dublin',
                  'London','London','London',
                  'Paris','Paris','Paris'],
         'year': [2018,2019,2020,
                  2018,2019,2020,
                  2018,2019,2020],
         'pop': [2.3,3.4,3.2,
                 4.3,4.4,4.2,
                 4.8,5.0,5.2]}
myClass

{'city': ['Dublin',
  'Dublin',
  'Dublin',
  'London',
  'London',
  'London',
  'Paris',
  'Paris',
  'Paris'],
 'year': [2018, 2019, 2020, 2018, 2019, 2020, 2018, 2019, 2020],
 'pop': [2.3, 3.4, 3.2, 4.3, 4.4, 4.2, 4.8, 5.0, 5.2]}

In [ ]:
import pandas as pd

myClass_df = pd.DataFrame(myClass)
myClass_df

     city  year  pop
0  Dublin  2018  2.3
1  Dublin  2019  3.4
2  Dublin  2020  3.2
3  London  2018  4.3
4  London  2019  4.4
5  London  2020  4.2
6   Paris  2018  4.8
7   Paris  2019  5.0
8   Paris  2020  5.2

In [ ]:
myClass_df['city'].head()

0    Dublin
1    Dublin
2    Dublin
3    London
4    London
Name: city, dtype: object

In [ ]:
type(myClass_df['city'])

pandas.core.series.Series

In [ ]:
myClass_df[['city','pop']].head()

     city  pop
0  Dublin  2.3
1  Dublin  3.4
2  Dublin  3.2
3  London  4.3
4  London  4.4

In [ ]:
type(myClass_df[['city','pop']])

pandas.core.frame.DataFrame

In [ ]:
myClass_df.rename(columns =
                  {'city':'capitcal city',
                   'pop':'population'},
                  inplace=False)

  capitcal city  year  population
0        Dublin  2018         2.3
1        Dublin  2019         3.4
2        Dublin  2020         3.2
3        London  2018         4.3
4        London  2019         4.4
5        London  2020         4.2
6         Paris  2018         4.8
7         Paris  2019         5.0
8         Paris  2020         5.2

In [ ]:
myClass_df['city'].unique()

array(['Dublin', 'London', 'Paris'], dtype=object)

In [ ]:
myClass_df['city'].nunique()

3

In [ ]:
myClass_df['city'].value_counts()

city
Dublin    3
London    3
Paris     3
Name: count, dtype: int64

In [ ]:
myClass_df['city'].value_counts(normalize=True)

city
Dublin    0.333333
London    0.333333
Paris     0.333333
Name: proportion, dtype: float64

### Import & Export

In [ ]:
import pandas as pd

sample_1 = pd.read_table('/content/drive/MyDrive/[YU]/[Lecture]/[SAM]/01_SAM_Practice/SAM_LEC03/sample_1.txt',
                         sep=',')
sample_1

   name  age        major
0   kim   23   management
1  park   22    economics
2   lee   22  engineering

In [ ]:
sample_1 = pd.read_csv('/content/drive/MyDrive/[YU]/[Lecture]/[SAM]/01_SAM_Practice/SAM_LEC03/sample_1.csv')
sample_1

    name  age        major  score grade
0    Kim   23   management   95.0     A
1   Park   22    economics    NaN     A
2    Lee   22  engineering    NaN     B
3   Choi   21       design   87.0     B
4    Han   21  engineering   86.0     B
5  Hwang   24    economics   85.0     B
6    Ban   23   management   82.0     B
7     Ki   20          law   78.0     C
8   Jang   24         math   75.0     C
9   Yang   23   statistics   68.0     D

In [ ]:
sample_1 = pd.read_csv('/content/drive/MyDrive/[YU]/[Lecture]/[SAM]/01_SAM_Practice/SAM_LEC03/sample_1.csv',
                       header=None)
sample_1

        0    1            2      3      4
0    name  age        major  score  grade
1     Kim   23   management     95      A
2    Park   22    economics    NaN      A
3     Lee   22  engineering    NaN      B
4    Choi   21       design     87      B
5     Han   21  engineering     86      B
6   Hwang   24    economics     85      B
7     Ban   23   management     82      B
8      Ki   20          law     78      C
9    Jang   24         math     75      C
10   Yang   23   statistics     68      D

In [ ]:
header_name=['FullName','Age','Major']
sample_1 = pd.read_csv('/content/drive/MyDrive/[YU]/[Lecture]/[SAM]/01_SAM_Practice/SAM_LEC03/sample_1.csv',
                       names=header_name)
sample_1

              FullName    Age  Major
name  age        major  score  grade
Kim   23    management     95      A
Park  22     economics    NaN      A
Lee   22   engineering    NaN      B
Choi  21        design     87      B
Han   21   engineering     86      B
Hwang 24     economics     85      B
Ban   23    management     82      B
Ki    20           law     78      C
Jang  24          math     75      C
Yang  23    statistics     68      D

In [ ]:
sample_2 = pd.read_csv('/content/drive/MyDrive/[YU]/[Lecture]/[SAM]/01_SAM_Practice/SAM_LEC03/sample_2.csv')
sample_2

   name  age        major hometown
0   kim   23   management    Seoul
1  park   22    economics    Paris
2   lee   22  engineering      NaN
3  kane   28          NaN  London

In [ ]:
# export sample_3.csv
sample_2.to_csv('/content/drive/MyDrive/[YU]/[Lecture]/[SAM]/01_SAM_Practice/SAM_LEC03/sample_3.csv')

In [ ]:
# export sample_4.csv
sample_2.to_csv('/content/drive/MyDrive/[YU]/[Lecture]/[SAM]/01_SAM_Practice/SAM_LEC03/sample_4.csv',sep='@')

In [ ]:
# export sample_5.csv
sample_2.to_csv('/content/drive/MyDrive/[YU]/[Lecture]/[SAM]/01_SAM_Practice/SAM_LEC03/sample_5.csv', header=False, index=False)

### Data Reshape

In [ ]:
import pandas as pd
import numpy as np
sample_1 = pd.read_csv('/content/drive/MyDrive/[YU]/[Lecture]/[SAM]/01_SAM_Practice/SAM_LEC03/sample_1.csv')
sample_1_wide = sample_1
sample_1_wide

    name  age        major  score grade
0    Kim   23   management   95.0     A
1   Park   22    economics    NaN     A
2    Lee   22  engineering    NaN     B
3   Choi   21       design   87.0     B
4    Han   21  engineering   86.0     B
5  Hwang   24    economics   85.0     B
6    Ban   23   management   82.0     B
7     Ki   20          law   78.0     C
8   Jang   24         math   75.0     C
9   Yang   23   statistics   68.0     D

In [ ]:
sample_1_wide.melt(id_vars='name',
                   value_vars=['age','major',
                               'score','grade'])

     name variable        value
0     Kim      age           23
1    Park      age           22
2     Lee      age           22
3    Choi      age           21
4     Han      age           21
5   Hwang      age           24
6     Ban      age           23
7      Ki      age           20
8    Jang      age           24
9    Yang      age           23
10    Kim    major   management
11   Park    major    economics
12    Lee    major  engineering
13   Choi    major       design
14    Han    major  engineering
15  Hwang    major    economics
16    Ban    major   management
17     Ki    major          law
18   Jang    major         math
19   Yang    major   statistics
20    Kim    score         95.0
21   Park    score          NaN
22    Lee    score          NaN
23   Choi    score         87.0
24    Han    score         86.0
25  Hwang    score         85.0
26    Ban    score         82.0
27     Ki    score         78.0
28   Jang    score         75.0
29   Yang    score         68.0
30    Kim    grade            A
31   Park    grade            A
32    Lee    grade            B
33   Choi    grade            B
34    Han    grade            B
35  Hwang    grade            B
36    Ban    grade            B
37     Ki    grade            C
38   Jang    grade            C
39   Yang    grade            D

In [ ]:
sample_1_wide.melt(id_vars='name',
                   value_vars=['age','major','score','grade'],
                   var_name='VariableType',
                   value_name='Amount').head()

   name VariableType Amount
0   Kim          age     23
1  Park          age     22
2   Lee          age     22
3  Choi          age     21
4   Han          age     21

In [ ]:
sample_1_long = sample_1_wide.melt(id_vars='name',value_vars=['age','major','score','grade'])
sample_1_long.rename(columns={'variable':'attribute','value':'amount'}, inplace=True)
sample_1_long.sort_values('name').head()

    name attribute      amount
26   Ban     score        82.0
16   Ban     major  management
36   Ban     grade           B
6    Ban       age          23
13  Choi     major      design

In [ ]:
sample_1_long.pivot(index='name',
                    columns='attribute',
                    values='amount')

attribute age grade        major score
name
Ban        23     B   management  82.0
Choi       21     B       design  87.0
Han        21     B  engineering  86.0
Hwang      24     B    economics  85.0
Jang       24     C         math  75.0
Ki         20     C          law  78.0
Kim        23     A   management  95.0
Lee        22     B  engineering   NaN
Park       22     A    economics   NaN
Yang       23     D   statistics  68.0

In [ ]:
sample_1_long_wide = sample_1_long.pivot(index='name',
                                         columns='attribute',
                                         values='amount')
sample_1_long_wide

attribute age grade        major score
name
Ban        23     B   management  82.0
Choi       21     B       design  87.0
Han        21     B  engineering  86.0
Hwang      24     B    economics  85.0
Jang       24     C         math  75.0
Ki         20     C          law  78.0
Kim        23     A   management  95.0
Lee        22     B  engineering   NaN
Park       22     A    economics   NaN
Yang       23     D   statistics  68.0

In [ ]:
sample_1_long.pivot(index='name',
                    columns='attribute',
                    values='amount').reset_index()

attribute   name age grade        major score
0            Ban  23     B   management  82.0
1           Choi  21     B       design  87.0
2            Han  21     B  engineering  86.0
3          Hwang  24     B    economics  85.0
4           Jang  24     C         math  75.0
5             Ki  20     C          law  78.0
6            Kim  23     A   management  95.0
7            Lee  22     B  engineering   NaN
8           Park  22     A    economics   NaN
9           Yang  23     D   statistics  68.0

#### Practice

In [ ]:
# Each student currently occupies one row. Explain why this is wide format.
import pandas as pd
survey = pd.DataFrame({
    "student_id": [101, 102, 103],
    "group": ["A", "B", "A"],
    "stress_before": [7, 5, 8],
    "stress_after": [4, 6, 5],
    "sleep_before": [5, 7, 4],
    "sleep_after": [7, 6, 6]
})
survey

   student_id group  stress_before  stress_after  sleep_before  sleep_after
0         101     A              7             4             5            7
1         102     B              5             6             7            6
2         103     A              8             5             4            6

In [ ]:
# Convert the four measurement columns into two columns named measure and value.
# Keep both student_id and group as identifiers.
survey_long = survey.melt(
    id_vars=["student_id", "group"],
    value_vars=[
        "stress_before", "stress_after",
        "sleep_before", "sleep_after"
    ],
    var_name="measure",
    value_name="value"
)
survey_long

    student_id group        measure  value
0          101     A  stress_before      7
1          102     B  stress_before      5
2          103     A  stress_before      8
3          101     A   stress_after      4
4          102     B   stress_after      6
5          103     A   stress_after      5
6          101     A   sleep_before      5
7          102     B   sleep_before      7
8          103     A   sleep_before      4
9          101     A    sleep_after      7
10         102     B    sleep_after      6
11         103     A    sleep_after      6

In [ ]:
# Restore the original wide structure.
survey_wide = (
    survey_long
    .pivot(
        index=["student_id", "group"],
        columns="measure",
        values="value"
    )
    .reset_index()
)
survey_wide

measure,student_id,group,sleep_after,sleep_before,stress_after,stress_before
0,101,A,7,5,4,7
1,102,B,6,7,6,5
2,103,A,6,4,5,8

### DataFrame Filtering

In [ ]:
myClass={'city': ['Dublin','Dublin','Dublin',
                  'London','London','London',
                  'Paris','Paris','Paris'],
         'year': [2018,2019,2020,
                  2018,2019,2020,
                  2018,2019,2020],
         'pop': [2.3,3.4,3.2,
                 4.3,4.4,4.2,
                 4.8,5.0,5.2]}
import pandas as pd

myClass_df = pd.DataFrame(myClass)
myClass_df

     city  year  pop
0  Dublin  2018  2.3
1  Dublin  2019  3.4
2  Dublin  2020  3.2
3  London  2018  4.3
4  London  2019  4.4
5  London  2020  4.2
6   Paris  2018  4.8
7   Paris  2019  5.0
8   Paris  2020  5.2

In [ ]:
myClass_df.iloc[0]

city    Dublin
year      2018
pop        2.3
Name: 0, dtype: object

In [ ]:
myClass_df.iloc[[0]]

     city  year  pop
0  Dublin  2018  2.3

In [ ]:
myClass_df.iloc[:2]

     city  year  pop
0  Dublin  2018  2.3
1  Dublin  2019  3.4

In [ ]:
myClass_df.iloc[:2,1:3]

   year  pop
0  2018  2.3
1  2019  3.4

In [ ]:
myClass_df.iloc[[0,3],1:3]

   year  pop
0  2018  2.3
3  2018  4.3

In [ ]:
myClass_df.iloc[[0,3],[0,2]]

     city  pop
0  Dublin  2.3
3  London  4.3

In [2]:
import pandas as pd
myClass_index=pd.DataFrame(
    {'city': ['Dublin','Dublin','Dublin',
              'London','London','London',
              'Paris','Paris','Paris'],
     'year': [2018,2019,2020,
              2018,2019,2020,
              2018,2019,2020],
     'pop': [2.3,3.4,3.2,
             4.3,4.4,4.2,
             4.8,5.0,5.2]},
     index=['Dublin2018','Dublin2019','Dublin2020',
            'London2018','London2019','London2020',
            'Paris2018','Paris2019','Paris2020'])
myClass_index

              city  year  pop
Dublin2018  Dublin  2018  2.3
Dublin2019  Dublin  2019  3.4
Dublin2020  Dublin  2020  3.2
London2018  London  2018  4.3
London2019  London  2019  4.4
London2020  London  2020  4.2
Paris2018    Paris  2018  4.8
Paris2019    Paris  2019  5.0
Paris2020    Paris  2020  5.2

In [ ]:
print(type(myClass_index.loc['Dublin2018']))
myClass_index.loc['Dublin2018']

<class 'pandas.core.series.Series'>

city    Dublin
year      2018
pop        2.3
Name: Dublin2018, dtype: object

In [ ]:
print(type(myClass_index.loc[['Dublin2018']]))
myClass_index.loc[['Dublin2018']]

<class 'pandas.core.frame.DataFrame'>

              city  year  pop
Dublin2018  Dublin  2018  2.3

In [ ]:
myClass_index.loc[['Dublin2018','Dublin2019']]

              city  year  pop
Dublin2018  Dublin  2018  2.3
Dublin2019  Dublin  2019  3.4

In [ ]:
myClass_index.loc[['Dublin2018','Dublin2019'],:]

              city  year  pop
Dublin2018  Dublin  2018  2.3
Dublin2019  Dublin  2019  3.4

In [ ]:
myClass_index['city']

Dublin2018    Dublin
Dublin2019    Dublin
Dublin2020    Dublin
London2018    London
London2019    London
London2020    London
Paris2018      Paris
Paris2019      Paris
Paris2020      Paris
Name: city, dtype: object

In [5]:
myClass_index.loc['Dublin2018']

city    Dublin
year      2018
pop        2.3
Name: Dublin2018, dtype: object

In [6]:
myClass_index.loc[:,'city']

Dublin2018    Dublin
Dublin2019    Dublin
Dublin2020    Dublin
London2018    London
London2019    London
London2020    London
Paris2018      Paris
Paris2019      Paris
Paris2020      Paris
Name: city, dtype: object

In [12]:
myClass_index['city']
# myClass_index.iloc[:,0]

              city  year  pop
Dublin2018  Dublin  2018  2.3
Dublin2019  Dublin  2019  3.4
Dublin2020  Dublin  2020  3.2
London2018  London  2018  4.3
London2019  London  2019  4.4
London2020  London  2020  4.2
Paris2018    Paris  2018  4.8
Paris2019    Paris  2019  5.0
Paris2020    Paris  2020  5.2

In [ ]:
myClass_index.loc[['Dublin2018']]

              city  year  pop
Dublin2018  Dublin  2018  2.3

In [ ]:
myClass_index.loc[['London2018','Paris2018']]

              city  year  pop
London2018  London  2018  4.3
Paris2018    Paris  2018  4.8

In [ ]:
myClass_index.loc['Dublin2018':'Paris2018','pop']

Dublin2018    2.3
Dublin2019    3.4
Dublin2020    3.2
London2018    4.3
London2019    4.4
London2020    4.2
Paris2018     4.8
Name: pop, dtype: float64

In [14]:
myClass_index.city=="Dublin"

Dublin2018     True
Dublin2019     True
Dublin2020     True
London2018    False
London2019    False
London2020    False
Paris2018     False
Paris2019     False
Paris2020     False
Name: city, dtype: bool

In [ ]:
myClass_index.loc[myClass_index.city=="Dublin"]

              city  year  pop
Dublin2018  Dublin  2018  2.3
Dublin2019  Dublin  2019  3.4
Dublin2020  Dublin  2020  3.2

In [ ]:
myClass_index.year==2018

Dublin2018     True
Dublin2019    False
Dublin2020    False
London2018     True
London2019    False
London2020    False
Paris2018      True
Paris2019     False
Paris2020     False
Name: year, dtype: bool

In [ ]:
myClass_index.loc[(myClass_index.city=="Dublin") & (myClass_index.year==2018)]

              city  year  pop
Dublin2018  Dublin  2018  2.3

In [ ]:
myClass_index.loc[myClass_index.city=="Dublin" & myClass_index.year==2018]

TypeError: Cannot perform 'rand_' with a dtyped [int64] array and scalar of type [bool]

#### Practice

In [ ]:
# Import “Most Subscribed YouTube Channels_exported.csv” to YoutubeSub.
# Given YoutubeSub, a data frame about YouTube Subscription, answer the following questions:

In [1]:
import pandas as pd

YoutubeSub = pd.read_csv("/content/drive/MyDrive/[YU]/[Lecture]/[SAM]/01_SAM_Practice/SAM_LEC03/Most Subscribed YouTube Channels_exported.csv")
YoutubeSub.head()

,Name,Brand channel,Subscribers (millions),Primary language,Category,Country
0,T-Series,Yes,249.0,Hindi[7][8],Music,India
1,MrBeast,No,184.0,English,Entertainment,United States
2,Cocomelon,Yes,165.0,English,Education,United States
3,Sony Entertainment Television India,Yes,162.0,Hindi[9],Entertainment,India
4,Kids Diana Show,Yes,113.0,English[10][11][12],Entertainment,Ukraine- United States

In [2]:
# 1) Which country has the greatest number of YouTube Channels?
YoutubeSub.Country.value_counts()

Country
India                           18
United States                   11
South Korea                      4
Russia- United States            2
Ukraine- United States           1
Sweden                           1
Cyprus[a]                        1
Canada                           1
Brazil                           1
Argentina                        1
Romania                          1
United Kingdom                   1
Chile                            1
Russia                           1
Belarus                          1
Mexico                           1
United States ( Puerto Rico)     1
Pakistan                         1
El Salvador                      1
Name: count, dtype: int64

In [3]:
YoutubeSub.Category=='Music'

0      True
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8      True
9     False
10     True
11    False
12    False
13    False
14     True
15     True
16    False
17     True
18    False
19    False
20     True
21    False
22     True
23     True
24    False
25    False
26    False
27     True
28    False
29     True
30     True
31     True
32     True
33     True
34    False
35     True
36     True
37     True
38    False
39     True
40    False
41    False
42     True
43    False
44     True
45    False
46    False
47     True
48    False
49    False
Name: Category, dtype: bool

In [6]:
# 2) What are the list of music-related YouTube Channels?
YoutubeSub.loc[YoutubeSub.Category=='Music',:].Name

0                   T-Series
8          Zee Music Company
10                 Blackpink
14                 BangtanTV
15               Hybe Labels
17             Justin Bieber
20           Canal KondZilla
22    Shemaroo Entertainment
23     T-Series Bhakti Sagar
27         El Reino Infantil
29                Wave Music
30          Sony Music India
31                    Eminem
32                Marshmello
33            Yash Raj Films
35               LooLoo Kids
36              Taylor Swift
37                Ed Sheeran
39             Ariana Grande
42             Billie Eilish
44        SonyMusicIndiaVEVO
47                 Bad Bunny
Name: Name, dtype: object

In [8]:
# 3) How many subscribers does Blackpink have?
YoutubeSub.loc[YoutubeSub.Name=="Blackpink"]

,Name,Brand channel,Subscribers (millions),Primary language,Category,Country
10,Blackpink,No,91.2,Korean,Music,South Korea

In [11]:
# 4) What is the most popular YouTube Channel?
YoutubeSub.loc[YoutubeSub['Subscribers (millions)'] == max(YoutubeSub['Subscribers (millions)'])]

,Name,Brand channel,Subscribers (millions),Primary language,Category,Country
0,T-Series,Yes,249.0,Hindi[7][8],Music,India

In [ ]:
YoutubeSub[['Name', 'Subscribers (millions)']].head()

                                  Name  Subscribers (millions)
0                             T-Series                   249.0
1                              MrBeast                   184.0
2                            Cocomelon                   165.0
3  Sony Entertainment Television India                   162.0
4                      Kids Diana Show                   113.0

In [ ]:
YoutubeSub.loc[:,['Name', 'Subscribers (millions)']].head()

                                  Name  Subscribers (millions)
0                             T-Series                   249.0
1                              MrBeast                   184.0
2                            Cocomelon                   165.0
3  Sony Entertainment Television India                   162.0
4                      Kids Diana Show                   113.0